"""
Email Formatter Module

This module provides functionality to format KPI analysis results
into well-structured markdown emails for dental practices.
"""

from typing import Dict, List, Any, Optional
import json

from src.utils.logging import get_logger

# Initialize logger
logger = get_logger(__name__)

def parse_json_response(response_content: str) -> Dict[str, Any]:
    """
    Parse the JSON response from the OpenAI Assistant.
    
    Args:
        response_content: The raw response content from the assistant
        
    Returns:
        A dictionary containing the parsed JSON data
        
    Raises:
        ValueError: If the response doesn't contain valid JSON
    """
    logger.info("Parsing JSON response from assistant")
    
    try:
        # Find JSON content in the response
        # This is a simplified approach assuming the JSON is enclosed in triple backticks
        json_start = response_content.find("```json")
        if json_start == -1:
            json_start = response_content.find("```")
            if json_start == -1:
                # No code blocks found, try to parse the entire response
                return json.loads(response_content)
                
        # Find the end of the JSON block
        json_start = response_content.find("\n", json_start) + 1
        json_end = response_content.find("```", json_start)
        
        if json_end == -1:
            # No closing code block, try to parse the rest of the response
            json_content = response_content[json_start:]
        else:
            json_content = response_content[json_start:json_end]
        
        # Parse the JSON
        parsed_data = json.loads(json_content)
        logger.info("Successfully parsed JSON response")
        return parsed_data
        
    except json.JSONDecodeError as e:
        error_msg = f"Failed to parse JSON from response: {str(e)}"
        logger.error(error_msg)
        raise ValueError(error_msg)
    except Exception as e:
        logger.error(f"Error parsing response: {str(e)}")
        raise

def format_email_markdown(parsed_data: Dict[str, Any]) -> str:
    """
    Format the parsed JSON data into a markdown email.
    
    Args:
        parsed_data: The parsed JSON data containing KPI analysis
        
    Returns:
        A markdown-formatted email string
        
    Raises:
        ValueError: If the parsed data doesn't contain required fields
    """
    logger.info("Formatting email markdown")
    
    try:
        # Validate required fields
        required_fields = ["subject", "summary", "kpi_analysis", "recommendations"]
        missing_fields = [field for field in required_fields if field not in parsed_data]
        
        if missing_fields:
            error_msg = f"Missing required fields in parsed data: {', '.join(missing_fields)}"
            logger.error(error_msg)
            raise ValueError(error_msg)
        
        # Start building the email
        markdown = []
        
        # Add subject as heading
        markdown.append(f"# {parsed_data['subject']}")
        markdown.append("")
        
        # Add summary
        markdown.append(parsed_data['summary'])
        markdown.append("")
        
        # Add KPI analysis
        markdown.append("## Key Performance Metrics")
        markdown.append("")
        
        for kpi in parsed_data['kpi_analysis']:
            # Add warning symbol for low-band KPIs
            prefix = "⚠️ " if kpi.get('status') == 'low' else ""
            
            # Bold key figures
            metric_value = f"**{kpi['value']}**" if 'value' in kpi else "N/A"
            metric_target = f"**{kpi['target']}**" if 'target' in kpi else "N/A"
            
            markdown.append(f"* {prefix}**{kpi['name']}**: {metric_value} vs target {metric_target}")
            
            # Add insight if available
            if 'insight' in kpi and kpi['insight']:
                markdown.append(f"  * {kpi['insight']}")
                
        markdown.append("")
        
        # Add recommendations
        markdown.append("## Recommendations")
        markdown.append("")
        
        for rec in parsed_data['recommendations']:
            markdown.append(f"* {rec}")
            
        markdown.append("")
        
        # Add footer
        markdown.append("---")
        markdown.append("*Generated by Dental Analytics Email Assistant*")
        
        # Join all parts with newlines
        email_markdown = "\n".join(markdown)
        
        # Check word count
        word_count = len(email_markdown.split())
        logger.info(f"Generated email markdown with {word_count} words")
        
        if word_count > 350:
            logger.warning(f"Email exceeds 350 word limit ({word_count} words)")
            
        return email_markdown
        
    except Exception as e:
        logger.error(f"Error formatting email: {str(e)}")
        raise

def format_response(response_content: str) -> str:
    """
    Process the raw assistant response and format it as a markdown email.
    
    This is the main function that encapsulates the entire formatting flow:
    1. Parse the JSON from the response
    2. Format the parsed data into a markdown email
    
    Args:
        response_content: The raw response content from the assistant
        
    Returns:
        A markdown-formatted email string
        
    Raises:
        ValueError: If the response can't be parsed or formatted properly
    """
    try:
        # Parse the JSON response
        parsed_data = parse_json_response(response_content)
        
        # Format the email
        email_markdown = format_email_markdown(parsed_data)
        
        return email_markdown
        
    except Exception as e:
        logger.error(f"Error formatting response: {str(e)}")
        raise 